# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oSjVefBoI1zBDXeHw9-4P0KK47rHFWIu
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data = pd.read_csv('https://api.covid19india.org/csv/latest/state_wise_daily.csv')

daily = data[data['Status'] == 'Confirmed']['TT']
#t=data[data['Status']=='Confirmed']['Date']

daily=list(daily)
print(np.shape(daily))
summ=[]
arg=int(len(daily)/7)
for v in range(7):
    s=0
    for i in range(arg):
        s=s+daily[v]
        v=v+7
    summ.append(s)
days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
summ=[summ[2],summ[3],summ[4],summ[5],summ[6],summ[0],summ[1]]
data=summ

#plotting data

explode = (0.08, 0.03, 0.03, 0.03, 0.15, 0.03,0.03) 
colors=("green","#a4b800","#e36500","#f13600","red","chartreuse","#d58e00") 
wp = { 'linewidth' : 1, 'edgecolor' : "green" } 
def func(pct, allvalues): 
    absolute = int(pct / 100.*np.sum(allvalues)) 
    return "{:.1f}%\n({:d} no. of cases)".format(pct, absolute) 

fig, ax = plt.subplots(figsize =(10, 10)) 
wedges, texts, autotexts = ax.pie(data,  
                                  autopct = lambda pct: func(pct, data), 
                                  explode = explode,  
                                  labels = days, 
                                  shadow = True, 
                                  colors = colors, 
                                  startangle = 90, 
                                  wedgeprops = wp, 
                                  textprops = dict(color ="black")) 

ax.legend(wedges, days, 
          title ="Days", 
          loc ="center left", 
          bbox_to_anchor =(1.1, 0, 0.5, 1)) 
plt.setp(autotexts, size = 8.5, weight ="bold") 
ax.set_title("Covid19 cases in India (Total cases {})".format(np.sum(daily)),color='red',weight='bold',size=13)
plt.tight_layout()
fig.savefig('Covid19 cases in India.png')